lokasi_list = sorted(set([
    "BULLSEYE", "HONGKONGPOOLS", 
    "HONGKONG LOTTO", "MOROCCO QUATRO00", "MOROCCO QUATRO01",
    "MOROCCO QUATRO02", "MOROCCO QUATRO03", "MOROCCO QUATRO04",
    "MOROCCO QUATRO05", "MOROCCO QUATRO06", "MOROCCO QUATRO15",
    "MOROCCO QUATRO16", "MOROCCO QUATRO17", "MOROCCO QUATRO18",
    "MOROCCO QUATRO19", "MOROCCO QUATRO20", "MOROCCO QUATRO21",
    "MOROCCO QUATRO22", "MOROCCO QUATRO23", 
    "SINGAPORE", "SYDNEYPOOLS", "SYDNEY LOTTO",
]))
